# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yufeng/research/others/compass

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yufeng/research/others/compass

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yufeng/research/others/compass/CMakeFiles /home/yufeng/research/others/compass/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yufeng/research/others/compass/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named util

# Build rule for target.
util: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 util
.PHONY : util

# fast build rule for target.
util/fast:
	$(MAKE) -f util/CMakeFiles/util.dir/build.make util/CMakeFiles/util.dir/build
.PHONY : util/fast

#=============================================================================
# Target rules for targets named sail

# Build rule for target.
sail: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sail
.PHONY : sail

# fast build rule for target.
sail/fast:
	$(MAKE) -f sail/CMakeFiles/sail.dir/build.make sail/CMakeFiles/sail.dir/build
.PHONY : sail/fast

#=============================================================================
# Target rules for targets named dex-parser

# Build rule for target.
dex-parser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dex-parser
.PHONY : dex-parser

# fast build rule for target.
dex-parser/fast:
	$(MAKE) -f dex-parser/CMakeFiles/dex-parser.dir/build.make dex-parser/CMakeFiles/dex-parser.dir/build
.PHONY : dex-parser/fast

#=============================================================================
# Target rules for targets named sail-test

# Build rule for target.
sail-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sail-test
.PHONY : sail-test

# fast build rule for target.
sail-test/fast:
	$(MAKE) -f sail-test/CMakeFiles/sail-test.dir/build.make sail-test/CMakeFiles/sail-test.dir/build
.PHONY : sail-test/fast

#=============================================================================
# Target rules for targets named mistral

# Build rule for target.
mistral: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mistral
.PHONY : mistral

# fast build rule for target.
mistral/fast:
	$(MAKE) -f mistral/CMakeFiles/mistral.dir/build.make mistral/CMakeFiles/mistral.dir/build
.PHONY : mistral/fast

#=============================================================================
# Target rules for targets named parser

# Build rule for target.
parser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 parser
.PHONY : parser

# fast build rule for target.
parser/fast:
	$(MAKE) -f mistral/parser/CMakeFiles/parser.dir/build.make mistral/parser/CMakeFiles/parser.dir/build
.PHONY : parser/fast

#=============================================================================
# Target rules for targets named smtparser

# Build rule for target.
smtparser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 smtparser
.PHONY : smtparser

# fast build rule for target.
smtparser/fast:
	$(MAKE) -f mistral/smtparser/CMakeFiles/smtparser.dir/build.make mistral/smtparser/CMakeFiles/smtparser.dir/build
.PHONY : smtparser/fast

#=============================================================================
# Target rules for targets named mistral_ui

# Build rule for target.
mistral_ui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mistral_ui
.PHONY : mistral_ui

# fast build rule for target.
mistral_ui/fast:
	$(MAKE) -f mistral/ui/CMakeFiles/mistral_ui.dir/build.make mistral/ui/CMakeFiles/mistral_ui.dir/build
.PHONY : mistral_ui/fast

#=============================================================================
# Target rules for targets named serialization

# Build rule for target.
serialization: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 serialization
.PHONY : serialization

# fast build rule for target.
serialization/fast:
	$(MAKE) -f serialization/CMakeFiles/serialization.dir/build.make serialization/CMakeFiles/serialization.dir/build
.PHONY : serialization/fast

#=============================================================================
# Target rules for targets named compass

# Build rule for target.
compass: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 compass
.PHONY : compass

# fast build rule for target.
compass/fast:
	$(MAKE) -f compass/CMakeFiles/compass.dir/build.make compass/CMakeFiles/compass.dir/build
.PHONY : compass/fast

#=============================================================================
# Target rules for targets named compass_ui

# Build rule for target.
compass_ui: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 compass_ui
.PHONY : compass_ui

# fast build rule for target.
compass_ui/fast:
	$(MAKE) -f compass/CMakeFiles/compass_ui.dir/build.make compass/CMakeFiles/compass_ui.dir/build
.PHONY : compass_ui/fast

#=============================================================================
# Target rules for targets named compass_ui_automoc

# Build rule for target.
compass_ui_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 compass_ui_automoc
.PHONY : compass_ui_automoc

# fast build rule for target.
compass_ui_automoc/fast:
	$(MAKE) -f compass/CMakeFiles/compass_ui_automoc.dir/build.make compass/CMakeFiles/compass_ui_automoc.dir/build
.PHONY : compass_ui_automoc/fast

#=============================================================================
# Target rules for targets named abductor

# Build rule for target.
abductor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 abductor
.PHONY : abductor

# fast build rule for target.
abductor/fast:
	$(MAKE) -f abductor/CMakeFiles/abductor.dir/build.make abductor/CMakeFiles/abductor.dir/build
.PHONY : abductor/fast

#=============================================================================
# Target rules for targets named dex-parser-test

# Build rule for target.
dex-parser-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dex-parser-test
.PHONY : dex-parser-test

# fast build rule for target.
dex-parser-test/fast:
	$(MAKE) -f dex-parser-test/CMakeFiles/dex-parser-test.dir/build.make dex-parser-test/CMakeFiles/dex-parser-test.dir/build
.PHONY : dex-parser-test/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... uninstall"
	@echo "... util"
	@echo "... sail"
	@echo "... dex-parser"
	@echo "... sail-test"
	@echo "... mistral"
	@echo "... parser"
	@echo "... smtparser"
	@echo "... mistral_ui"
	@echo "... serialization"
	@echo "... compass"
	@echo "... compass_ui"
	@echo "... compass_ui_automoc"
	@echo "... abductor"
	@echo "... dex-parser-test"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

